---
name: verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: tests
        run: make setup tests

      - name: lint
        run: make setup lint
